language: cpp

compiler:
    - gcc
    - clang

os:
    - linux

matrix:
    allow_failures:
        - os: osx

dist: trusty
sudo: false

env:
    - ASAN_OPTIONS=detect_odr_violation=0

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
        packages:
            - openssl
            - python3
            - gcc-7
            - g++-7
            - valgrind
            - bc
            - clang-4.0

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-4.0" CC="clang-4.0"; fi
