language: cpp

sudo: required

compiler:
    - gcc
    - clang

os:
    - linux

matrix:
    allow_failures:
        - os: osx

sudo: false

env:
    - ASAN_OPTIONS=detect_odr_violation=0

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
        packages:
            - openssl
            - python3
            - gcc-6
            - g++-6
            - valgrind
            - bc
            - clang-3.9

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi
