language: cpp

compiler:
    - gcc
    - clang

os:
    - linux

matrix:
    allow_failures:
        - os: osx

sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - openssl
            - python3
            - gcc-5
            - g++-5
            - valgrind
            - bc
    coverity_scan:
        project:
            name: "marekjm/viuavm"
        description: "Viua VM"
        notification_email: marekjm@ozro.pw
        build_command_prepend: "./configure"
        build_command:   "make -j 4"
        branch_pattern: coverity_scan

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
