language: cpp

compiler:
    - gcc
    - clang

os:
    - linux

matrix:
    allow_failures:
        - os: osx

sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
        packages:
            - openssl
            - python3
            - gcc-6
            - g++-6
            - valgrind
            - bc
            - clang-3.9
    coverity_scan:
        project:
            name: "marekjm/viuavm"
        description: "Viua VM"
        notification_email: marekjm@ozro.pw
        build_command_prepend: "./configure"
        build_command:   "make"
        branch_pattern: coverity_scan

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "X+v3Omn3qdxcrzGzfSgraqWXlBcFMljv8PKDGcff62eFRdVD/nolr2MX9BQevTuNjr/LYPcqDT3bS80mxOuJl3X7byXm8u8o+9e4/shEhPsfuGw6DV2xHnivvSNg34Tf5c2/xYP+karfN+oObury37F3ddsWQwLLFf0ZjoI9lto=" 
