language: cpp

compiler:
    - gcc

sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - openssl
            - python3
            - gcc-5
            - g++-5
            - valgrind

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
